[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
    "cd client && npm install",
    "cd server && npm install"
]

[phases.build]
cmds = [
    "cd client && npm run build",
    "cd server && npx prisma generate && npm run build"
]

[start]
cmd = "cd server && npx prisma migrate deploy && npm run start"
