[build]
builder = "nixpacks"

[build.env]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && npm run start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
